/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-03-02 03:47:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.fragment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- partial -->\r\n");
      out.write("      <!-- partial:partials/_sidebar.html -->\r\n");
      out.write("      <nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("        <ul class=\"nav\">\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("              <i class=\"icon-grid menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Dashboard</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#ui-basic\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("              <i class=\"icon-layout menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">UI Elements</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"ui-basic\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/buttons.html\">Buttons</a></li>\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/dropdowns.html\">Dropdowns</a></li>\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/ui-features/typography.html\">Typography</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#form-elements\" aria-expanded=\"false\" aria-controls=\"form-elements\">\r\n");
      out.write("              <i class=\"icon-columns menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Form elements</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"form-elements\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"pages/forms/basic_elements.html\">Basic Elements</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#charts\" aria-expanded=\"false\" aria-controls=\"charts\">\r\n");
      out.write("              <i class=\"icon-bar-graph menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Charts</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"charts\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/charts/chartjs.html\">ChartJs</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#tables\" aria-expanded=\"false\" aria-controls=\"tables\">\r\n");
      out.write("              <i class=\"icon-grid-2 menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Tables</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"tables\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/tables/basic-table.html\">Basic table</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#icons\" aria-expanded=\"false\" aria-controls=\"icons\">\r\n");
      out.write("              <i class=\"icon-contract menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Icons</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"icons\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/icons/mdi.html\">Mdi icons</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#auth\" aria-expanded=\"false\" aria-controls=\"auth\">\r\n");
      out.write("              <i class=\"icon-head menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">User Pages</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"auth\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"/loginForm.kmj\"> Login </a></li>\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"/register.kmj\"> Register </a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" data-toggle=\"collapse\" href=\"#error\" aria-expanded=\"false\" aria-controls=\"error\">\r\n");
      out.write("              <i class=\"icon-ban menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Error pages</span>\r\n");
      out.write("              <i class=\"menu-arrow\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"error\">\r\n");
      out.write("              <ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/samples/error-404.html\"> 404 </a></li>\r\n");
      out.write("                <li class=\"nav-item\"> <a class=\"nav-link\" href=\"pages/samples/error-500.html\"> 500 </a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"pages/documentation/documentation.html\">\r\n");
      out.write("              <i class=\"icon-paper menu-icon\"></i>\r\n");
      out.write("              <span class=\"menu-title\">Documentation</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
