/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-03-02 14:43:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\"><head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title>REGISTER</title>\r\n");
      out.write("  <!-- plugins:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/feather/feather.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/ti-icons/css/themify-icons.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- Plugin css for this page -->\r\n");
      out.write("  <!-- End plugin css for this page -->\r\n");
      out.write("  <!-- inject:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../css/vertical-layout-light/style.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"../../images/welcome.jpg\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	//회원가입 버튼 클릭시\r\n");
      out.write("	//$(document).on(\"click\", \"#register\", function(){\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	   console.log(\"register >>>> : \" );\r\n");
      out.write("	   \r\n");
      out.write("	   /*var mid = $(\"#mid\").val();\r\n");
      out.write("	   console.log(\"mid\" + mid);*/\r\n");
      out.write("	   $(\"#submit\").on(\"click\", function(){\r\n");
      out.write("			if($(\"#mid\").val()==\"\"){\r\n");
      out.write("				alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("				$(\"#mid\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if($(\"#mpw\").val()==\"\"){\r\n");
      out.write("				alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("				$(\"#mpw\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if($(\"#mname\").val()==\"\"){\r\n");
      out.write("				alert(\"성명을 입력해주세요.\");\r\n");
      out.write("				$(\"#mname\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			alert(\"회원가입이 완료 되었습니다!\");\r\n");
      out.write("	   //controller memInsert로 이동\r\n");
      out.write("	   $('#user').attr({\r\n");
      out.write("	      'action': 'memberInsert.kmj',\r\n");
      out.write("	      'method' : 'POST',\r\n");
      out.write("	      'enctype' : 'application/x-www-form-urlencoded'\r\n");
      out.write("	   }).submit();  \r\n");
      out.write("	});\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container-scroller\">\r\n");
      out.write("    <div class=\"container-fluid page-body-wrapper full-page-wrapper\">\r\n");
      out.write("      <div class=\"content-wrapper d-flex align-items-center auth px-0\">\r\n");
      out.write("        <div class=\"row w-100 mx-0\">\r\n");
      out.write("          <div class=\"col-lg-4 mx-auto\">\r\n");
      out.write("            <div class=\"auth-form-light text-left py-5 px-4 px-sm-5\">\r\n");
      out.write("              <div class=\"brand-logo\">\r\n");
      out.write("       			 <img src=\"../../images/welcome.jpg\" alt=\"welcome\"></div>\r\n");
      out.write("              <h6>SIGN UP</h6>\r\n");
      out.write("              <h6 class=\"font-weight-light\">환영합니다! 회원가입을 진행해주세요!</h6>\r\n");
      out.write("              \r\n");
      out.write("              <form name=\"user\" id=\"user\" class=\"pt-3\">\r\n");
      out.write("              \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"text\" id=\"mid\" name=\"mid\" placeholder=\"ID\" class=\"form-control form-control-lg\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"password\" id=\"mpw\" name=\"mpw\" placeholder=\"PassWord\" class=\"form-control form-control-lg\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"text\" id=\"mname\" name=\"mname\" placeholder=\"Username\" class=\"form-control form-control-lg\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mt-3\">\r\n");
      out.write("                  <button type=\"submit\" id=\"submit\"  class=\"btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn\">SIGN UP</button>\r\n");
      out.write("                </div><!-- onclick=\"location.href='loginForm.kmj'\" -->\r\n");
      out.write("                <div class=\"text-center mt-4 font-weight-light\">\r\n");
      out.write("                  	계정이 있으신가요? <a href=\"loginForm.kmj\" class=\"text-primary\">Login</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- content-wrapper ends -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- page-body-wrapper ends -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- container-scroller -->\r\n");
      out.write("  <!-- plugins:js -->\r\n");
      out.write("  <script src=\"../../vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- Plugin js for this page -->\r\n");
      out.write("  <!-- End plugin js for this page -->\r\n");
      out.write("  <!-- inject:js -->\r\n");
      out.write("  <script src=\"../../js/off-canvas.js\"></script>\r\n");
      out.write("  <script src=\"../../js/hoverable-collapse.js\"></script>\r\n");
      out.write("  <script src=\"../../js/template.js\"></script>\r\n");
      out.write("  <script src=\"../../js/settings.js\"></script>\r\n");
      out.write("  <script src=\"../../js/todolist.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
