/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-03-03 12:53:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\"><head>\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title>Study Project</title>\r\n");
      out.write("  <!-- plugins:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/feather/feather.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/ti-icons/css/themify-icons.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- Plugin css for this page -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/datatables.net-bs4/dataTables.bootstrap4.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/ti-icons/css/themify-icons.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"js/select.dataTables.min.css\">\r\n");
      out.write("  <!-- End plugin css for this page -->\r\n");
      out.write("  <!-- inject:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/vertical-layout-light/style.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"images/favicon.png\">\r\n");
      out.write("<style type=\"text/css\">/* Chart.js */\r\n");
      out.write("@keyframes chartjs-render-animation{from{opacity:.99}to{opacity:1}}.chartjs-render-monitor{animation:chartjs-render-animation 1ms}.chartjs-size-monitor,.chartjs-size-monitor-expand,.chartjs-size-monitor-shrink{position:absolute;direction:ltr;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1}.chartjs-size-monitor-expand>div{position:absolute;width:1000000px;height:1000000px;left:0;top:0}.chartjs-size-monitor-shrink>div{position:absolute;width:200%;height:200%;left:0;top:0}</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container-scroller\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- head -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.kmj", out, false);
      out.write("\r\n");
      out.write("    <!--<c:import url=\"head.kmj\" /> -->\r\n");
      out.write("    <!-- end of head -->\r\n");
      out.write("    <h8><a href=\"loginForm.kmj\">스프링 회원 : 로그인</a></h8>\r\n");
      out.write("    <!-- partial -->\r\n");
      out.write("    <div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("      <!-- partial:partials/_settings-panel.html -->\r\n");
      out.write("      <div class=\"theme-setting-wrapper\">\r\n");
      out.write("        <div id=\"settings-trigger\"><i class=\"ti-settings\"></i></div>\r\n");
      out.write("        <div id=\"theme-settings\" class=\"settings-panel\">\r\n");
      out.write("          <i class=\"settings-close ti-close\"></i>\r\n");
      out.write("          <p class=\"settings-heading\">SIDEBAR SKINS</p>\r\n");
      out.write("          <div class=\"sidebar-bg-options selected\" id=\"sidebar-light-theme\"><div class=\"img-ss rounded-circle bg-light border mr-3\"></div>Light</div>\r\n");
      out.write("          <div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\"><div class=\"img-ss rounded-circle bg-dark border mr-3\"></div>Dark</div>\r\n");
      out.write("          <p class=\"settings-heading mt-2\">HEADER SKINS</p>\r\n");
      out.write("          <div class=\"color-tiles mx-0 px-4\">\r\n");
      out.write("            <div class=\"tiles success\"></div>\r\n");
      out.write("            <div class=\"tiles warning\"></div>\r\n");
      out.write("            <div class=\"tiles danger\"></div>\r\n");
      out.write("            <div class=\"tiles info\"></div>\r\n");
      out.write("            <div class=\"tiles dark\"></div>\r\n");
      out.write("            <div class=\"tiles default\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"right-sidebar\" class=\"settings-panel\">\r\n");
      out.write("        <i class=\"settings-close ti-close\"></i>\r\n");
      out.write("        <ul class=\"nav nav-tabs border-top\" id=\"setting-panel\" role=\"tablist\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" id=\"todo-tab\" data-toggle=\"tab\" href=\"#todo-section\" role=\"tab\" aria-controls=\"todo-section\" aria-expanded=\"true\">TO DO LIST</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" id=\"chats-tab\" data-toggle=\"tab\" href=\"#chats-section\" role=\"tab\" aria-controls=\"chats-section\">CHATS</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"tab-content\" id=\"setting-content\">\r\n");
      out.write("          <div class=\"tab-pane fade show active scroll-wrapper ps ps--active-y\" id=\"todo-section\" role=\"tabpanel\" aria-labelledby=\"todo-section\">\r\n");
      out.write("            <div class=\"add-items d-flex px-3 mb-0\">\r\n");
      out.write("              <form class=\"form w-100\">\r\n");
      out.write("                <div class=\"form-group d-flex\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control todo-list-input\" placeholder=\"Add To-do\">\r\n");
      out.write("                  <button type=\"submit\" class=\"add btn btn-primary todo-list-add-btn\" id=\"add-task\">Add</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"list-wrapper px-3\">\r\n");
      out.write("              <ul class=\"d-flex flex-column-reverse todo-list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\r\n");
      out.write("                      Team review meeting at 3.00 PM\r\n");
      out.write("                    <i class=\"input-helper\"></i></label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"remove ti-close\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\r\n");
      out.write("                      Prepare for presentation\r\n");
      out.write("                    <i class=\"input-helper\"></i></label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"remove ti-close\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\">\r\n");
      out.write("                      Resolve all the low priority tickets due today\r\n");
      out.write("                    <i class=\"input-helper\"></i></label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"remove ti-close\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"completed\">\r\n");
      out.write("                  <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\" checked=\"\">\r\n");
      out.write("                      Schedule meeting for next week\r\n");
      out.write("                    <i class=\"input-helper\"></i></label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"remove ti-close\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"completed\">\r\n");
      out.write("                  <div class=\"form-check\">\r\n");
      out.write("                    <label class=\"form-check-label\">\r\n");
      out.write("                      <input class=\"checkbox\" type=\"checkbox\" checked=\"\">\r\n");
      out.write("                      Project review\r\n");
      out.write("                    <i class=\"input-helper\"></i></label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <i class=\"remove ti-close\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h4 class=\"px-3 text-muted mt-5 font-weight-light mb-0\">Events</h4>\r\n");
      out.write("            <div class=\"events pt-4 px-3\">\r\n");
      out.write("              <div class=\"wrapper d-flex mb-2\">\r\n");
      out.write("                <i class=\"ti-control-record text-primary mr-2\"></i>\r\n");
      out.write("                <span>Feb 11 2018</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <p class=\"mb-0 font-weight-thin text-gray\">Creating component page build a js</p>\r\n");
      out.write("              <p class=\"text-gray mb-0\">The total number of sessions</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"events pt-4 px-3\">\r\n");
      out.write("              <div class=\"wrapper d-flex mb-2\">\r\n");
      out.write("                <i class=\"ti-control-record text-primary mr-2\"></i>\r\n");
      out.write("                <span>Feb 7 2018</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <p class=\"mb-0 font-weight-thin text-gray\">Meeting with Alisa</p>\r\n");
      out.write("              <p class=\"text-gray mb-0 \">Call Sarah Graves</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"ps__rail-x\" style=\"left: 0px; bottom: 0px;\"><div class=\"ps__thumb-x\" tabindex=\"0\" style=\"left: 0px; width: 0px;\"></div></div><div class=\"ps__rail-y\" style=\"top: 0px; height: 754px; right: 0px;\"><div class=\"ps__thumb-y\" tabindex=\"0\" style=\"top: 0px; height: 633px;\"></div></div></div>\r\n");
      out.write("          <!-- To do section tab ends -->\r\n");
      out.write("          <div class=\"tab-pane fade\" id=\"chats-section\" role=\"tabpanel\" aria-labelledby=\"chats-section\">\r\n");
      out.write("            <div class=\"d-flex align-items-center justify-content-between border-bottom\">\r\n");
      out.write("              <p class=\"settings-heading border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0\">Friends</p>\r\n");
      out.write("              <small class=\"settings-heading border-top-0 mb-3 pt-0 border-bottom-0 pb-0 pr-3 font-weight-normal\">See All</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"chat-list\">\r\n");
      out.write("              <li class=\"list active\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face1.jpg\" alt=\"image\"><span class=\"online\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <p>Thomas Douglas</p>\r\n");
      out.write("                  <p>Available</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">19 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face2.jpg\" alt=\"image\"><span class=\"offline\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <div class=\"wrapper d-flex\">\r\n");
      out.write("                    <p>Catherine</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p>Away</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"badge badge-success badge-pill my-auto mx-2\">4</div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">23 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face3.jpg\" alt=\"image\"><span class=\"online\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <p>Daniel Russell</p>\r\n");
      out.write("                  <p>Available</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">14 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face4.jpg\" alt=\"image\"><span class=\"offline\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <p>James Richardson</p>\r\n");
      out.write("                  <p>Away</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">2 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face5.jpg\" alt=\"image\"><span class=\"online\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <p>Madeline Kennedy</p>\r\n");
      out.write("                  <p>Available</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">5 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list\">\r\n");
      out.write("                <div class=\"profile\"><img src=\"images/faces/face6.jpg\" alt=\"image\"><span class=\"online\"></span></div>\r\n");
      out.write("                <div class=\"info\">\r\n");
      out.write("                  <p>Sarah Graves</p>\r\n");
      out.write("                  <p>Available</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <small class=\"text-muted my-auto\">47 min</small>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- chat tab ends -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("     <!-- sidebar -->\r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.kmj", out, false);
      out.write("\r\n");
      out.write("     <!-- end of sidebar -->\r\n");
      out.write("     \r\n");
      out.write("     <!-- content -->\r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "content.kmj", out, false);
      out.write("\r\n");
      out.write("     <!--<c:import url=\"/content.kmj\"></c:import>-->\r\n");
      out.write("      <!-- End of content -->\r\n");
      out.write("     \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- content-wrapper ends -->\r\n");
      out.write("\r\n");
      out.write("		<!-- footer -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.kmj", out, false);
      out.write("\r\n");
      out.write("		<!-- end of footer -->\r\n");
      out.write("		\r\n");
      out.write("        <!-- partial -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- main-panel ends -->\r\n");
      out.write("    </div>   \r\n");
      out.write("    \r\n");
      out.write("    <!-- page-body-wrapper ends -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- container-scroller -->\r\n");
      out.write("\r\n");
      out.write("  <!-- plugins:js -->\r\n");
      out.write("  <script src=\"vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  \r\n");
      out.write("  <!-- Plugin js for this page -->\r\n");
      out.write("  <script src=\"vendors/chart.js/Chart.min.js\"></script>\r\n");
      out.write("  <script src=\"vendors/datatables.net/jquery.dataTables.js\"></script>\r\n");
      out.write("  <script src=\"vendors/datatables.net-bs4/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("  <script src=\"js/dataTables.select.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- End plugin js for this page -->\r\n");
      out.write("  <!-- inject:js -->\r\n");
      out.write("  <script src=\"js/off-canvas.js\"></script>\r\n");
      out.write("  <script src=\"js/hoverable-collapse.js\"></script>\r\n");
      out.write("  <script src=\"js/template.js\"></script>\r\n");
      out.write("  <script src=\"js/settings.js\"></script>\r\n");
      out.write("  <script src=\"js/todolist.js\"></script>\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- Custom js for this page-->\r\n");
      out.write("  <script src=\"js/dashboard.js\"></script>\r\n");
      out.write("  <script src=\"js/Chart.roundedBarCharts.js\"></script>\r\n");
      out.write("  <!-- End custom js for this page-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
